# Generated by Django 4.1.2 on 2022-10-18 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App1", "0003_humans_delete_geeksmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeeksModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
            ],
        ),
        migrations.DeleteModel(name="Humans",),
    ]
